apiVersion: apps/v1
kind: Deployment
metadata: 
  name: bknd-restapp
  labels:
    app: bknd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-restapp
  template:
    metadata:
      labels:
        app: backend-restapp
        tier: backend
    spec:
      containers:
        - name: backend-app
          image: stacksimplify/kube-helloworld:1.0.0